### PR TITLE
initial German translation

### PR DESCRIPTION
**Pull request by mmoole**
here is a German translation, I hope I didn't make too much typos etc.

### CODE REVIEW

**Comment by davidlesieur** [comment]
I can't comment on the language, but it looks good! :-)

The only issue I find is missing quotes in the beginning of line 435. If you can fix it, I'll gladly merge this. Thanks!

**Comment by mmoole** [comment]
now I added the missing quotes, and also changed one word to be better understandable.

Is there a linter for those .po files (for example for Atom)? I quickly searched, but didn't find something useful...

**Comment by davidlesieur** [comment]
Thanks for this!

**Comment by davidlesieur** [comment]
About the linter question, unfortunately I'm not aware of a good tool (personally, I edit those files with the gettext extension for vscode, but it is no linter). However, compiling the PO file as mentioned in the Kerko README is a quick way to detect obvious errors, which is how I found the missing quotes.

**Pull request merged**
